
###
POST http://localhost:3111/auth/register
Content-Type: application/json

{
    "name": "d", 
    "email": "d",
    "password": "d"
}

###

POST http://localhost:3111/auth/login
Content-Type: application/json

{
    "email": "b",
    "password": "b"
}

###

http://localhost:3111/auth/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjM2YTQyYjFiY2I1YzY0ZjRhODQ5YTEiLCJpYXQiOjE2NDc3NDgxNTgsImV4cCI6MTY0Nzc0ODE4OH0.iKRRO-Gyshzdc5JYWZwyNxsj4ocNsRg2qrs-jk40xH4

###

POST http://localhost:3111/auth/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjM2YTQyYjFiY2I1YzY0ZjRhODQ5YTEiLCJpYXQiOjE2NDc3NDgxNTh9.6gIKf7R-w5jI6IlhzM__p9nwSrBHTVFAsQZBX-VGN9o"
}

###

DELETE http://localhost:3111/auth/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjM2YTQyYjFiY2I1YzY0ZjRhODQ5YTEiLCJpYXQiOjE2NDc3NDgxNTh9.6gIKf7R-w5jI6IlhzM__p9nwSrBHTVFAsQZBX-VGN9o"
}

 