
###
POST http://localhost:3112/auth/register
Content-Type: application/json

{
    "name": "11", 
    "email": "11",
    "password": "11"
}

###

POST http://localhost:3112/auth/login
Content-Type: application/json

{
    "email": "22",
    "password": "22"
}

###

http://localhost:3112/auth/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjNkZjI0NzNhYmYwMDliNDliM2ViODQiLCJpYXQiOjE2NDgyNDMwMjgsImV4cCI6MTY0ODI0MzA1MH0.ggFAzkk-mjaDBtns2V3ra36EOGq4Lcp_0WdiHmsWb0o



###

POST http://localhost:3112/auth/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjNkZjI0NzNhYmYwMDliNDliM2ViODQiLCJpYXQiOjE2NDgyNDI5NDB9.ADnKzfbVcVRvcyRTbW5uhExD70_GEem-ZWOfLmZz5as"
}

###

DELETE http://localhost:3112/auth/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjNkZjI0NzNhYmYwMDliNDliM2ViODQiLCJpYXQiOjE2NDgyNDI5NDB9.ADnKzfbVcVRvcyRTbW5uhExD70_GEem-ZWOfLmZz5as"
}

 