
###
POST http://localhost:3112/auth/register
Content-Type: application/json

{
    "name": "33", 
    "email": "33",
    "password": "33"
}

###

POST http://localhost:3112/auth/login
Content-Type: application/json

{
    "email": "33",
    "password": "33"
}

###

http://localhost:3112/auth/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjNhYmFiYWNjYjc3Yjg0YzNhNzUzODQiLCJpYXQiOjE2NDgwMTYxMDksImV4cCI6MTY0ODAxNjEzOX0.GnOq3MpEwWW0rWoazot7hwg1X8dcfthggxImUYLrcWA



###

POST http://localhost:3112/auth/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjNhYmFiYWNjYjc3Yjg0YzNhNzUzODQiLCJpYXQiOjE2NDgwMTYxMDl9.rSzNdhTq5lpMJ_20pR4BHo04CFecoI-nIP9P-s3WgH0"
}

###

DELETE http://localhost:3112/auth/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjNhYmFiYWNjYjc3Yjg0YzNhNzUzODQiLCJpYXQiOjE2NDgwMTYxMDl9.rSzNdhTq5lpMJ_20pR4BHo04CFecoI-nIP9P-s3WgH0"
}

 